export type BadgeTone = "neutral" | "positive" | "warning" | "danger" | "info";

export const overviewMetrics = [
  {
    label: "Active identities",
    value: "1,248",
    detail: "+32 this month",
    trend: "positive" as const,
  },
  {
    label: "Privileged paths",
    value: "47",
    detail: "8 require review",
    trend: "warning" as const,
  },
  {
    label: "Open requests",
    value: "18",
    detail: "6 due today",
    trend: "danger" as const,
  },
  {
    label: "Policy coverage",
    value: "93.6%",
    detail: "+2.1 pts this quarter",
    trend: "positive" as const,
  },
];

export const accessRequests = [
  {
    id: "REQ-1048",
    requester: "Maya Chen",
    initials: "MC",
    resource: "Production billing",
    entitlement: "Read + export",
    risk: "High",
    riskTone: "danger" as BadgeTone,
    age: "42 min",
    status: "Needs review",
    statusTone: "warning" as BadgeTone,
  },
  {
    id: "REQ-1047",
    requester: "Theo Martin",
    initials: "TM",
    resource: "Customer analytics",
    entitlement: "Editor",
    risk: "Medium",
    riskTone: "warning" as BadgeTone,
    age: "1 hr",
    status: "Manager approved",
    statusTone: "info" as BadgeTone,
  },
  {
    id: "REQ-1046",
    requester: "Nadia Okafor",
    initials: "NO",
    resource: "Support console",
    entitlement: "Temporary admin",
    risk: "Critical",
    riskTone: "danger" as BadgeTone,
    age: "2 hrs",
    status: "Security review",
    statusTone: "danger" as BadgeTone,
  },
  {
    id: "REQ-1045",
    requester: "Jon Bell",
    initials: "JB",
    resource: "Design system",
    entitlement: "Contributor",
    risk: "Low",
    riskTone: "positive" as BadgeTone,
    age: "4 hrs",
    status: "Auto-approved",
    statusTone: "positive" as BadgeTone,
  },
  {
    id: "REQ-1044",
    requester: "Priya Shah",
    initials: "PS",
    resource: "Finance warehouse",
    entitlement: "Query runner",
    risk: "Medium",
    riskTone: "warning" as BadgeTone,
    age: "Yesterday",
    status: "Needs review",
    statusTone: "warning" as BadgeTone,
  },
];

export const auditEvents = [
  {
    time: "09:42",
    title: "Privileged role removed",
    detail: "Platform Admin removed from Theo Martin by lifecycle policy.",
    actor: "Lifecycle bot",
    tone: "positive" as BadgeTone,
  },
  {
    time: "09:18",
    title: "Policy exception created",
    detail: "Temporary export access granted to Maya Chen until Sep 04.",
    actor: "Leah Young",
    tone: "warning" as BadgeTone,
  },
  {
    time: "08:56",
    title: "Risky path detected",
    detail: "Contractor group can reach Production AWS through a nested role.",
    actor: "Graph monitor",
    tone: "danger" as BadgeTone,
  },
  {
    time: "08:21",
    title: "Quarterly review completed",
    detail: "Finance Ops review closed with 18 entitlements certified.",
    actor: "Amira Solberg",
    tone: "info" as BadgeTone,
  },
  {
    time: "Yesterday",
    title: "Directory sync completed",
    detail: "1,248 identities reconciled with the workforce directory.",
    actor: "Directory sync",
    tone: "neutral" as BadgeTone,
  },
];

export const riskItems = [
  {
    id: "RISK-032",
    title: "Dormant privileged accounts",
    scope: "Production AWS",
    owner: "Cloud Platform",
    severity: "Critical",
    tone: "danger" as BadgeTone,
    exposure: "5 identities",
    due: "Today",
  },
  {
    id: "RISK-031",
    title: "Unbounded export permission",
    scope: "Billing warehouse",
    owner: "Finance Systems",
    severity: "High",
    tone: "danger" as BadgeTone,
    exposure: "14 identities",
    due: "Sep 02",
  },
  {
    id: "RISK-029",
    title: "Nested contractor access",
    scope: "Support console",
    owner: "Customer Operations",
    severity: "High",
    tone: "danger" as BadgeTone,
    exposure: "9 identities",
    due: "Sep 04",
  },
  {
    id: "RISK-027",
    title: "Missing access expiry",
    scope: "Analytics workspace",
    owner: "Data Platform",
    severity: "Medium",
    tone: "warning" as BadgeTone,
    exposure: "22 identities",
    due: "Sep 09",
  },
];

export const riskyPaths = [
  {
    identity: "Nadia Okafor",
    via: "Contractors → Support Admin",
    resource: "Production support",
    privilege: "Impersonate customer",
    score: 94,
  },
  {
    identity: "Maya Chen",
    via: "Finance Ops → Exporters",
    resource: "Billing warehouse",
    privilege: "Bulk export",
    score: 87,
  },
  {
    identity: "Service: ci-release",
    via: "Build Agents → Platform",
    resource: "Production AWS",
    privilege: "Deploy + secrets",
    score: 82,
  },
  {
    identity: "Jon Bell",
    via: "Design → Shared Tools",
    resource: "Customer analytics",
    privilege: "Dataset viewer",
    score: 48,
  },
];

export const graphNodes = [
  { id: "maya", label: "Maya Chen", kind: "identity" as const, x: 92, y: 72 },
  { id: "nadia", label: "Nadia Okafor", kind: "identity" as const, x: 92, y: 188 },
  { id: "service", label: "ci-release", kind: "service" as const, x: 92, y: 304 },
  { id: "finance", label: "Finance Ops", kind: "group" as const, x: 280, y: 72 },
  { id: "contractors", label: "Contractors", kind: "group" as const, x: 280, y: 188 },
  { id: "agents", label: "Build Agents", kind: "group" as const, x: 280, y: 304 },
  { id: "exporters", label: "Exporters", kind: "role" as const, x: 470, y: 72 },
  { id: "support-admin", label: "Support Admin", kind: "role" as const, x: 470, y: 188 },
  { id: "platform", label: "Platform", kind: "role" as const, x: 470, y: 304 },
  { id: "billing", label: "Billing warehouse", kind: "resource" as const, x: 680, y: 72 },
  { id: "support", label: "Production support", kind: "resource" as const, x: 680, y: 188 },
  { id: "aws", label: "Production AWS", kind: "resource" as const, x: 680, y: 304 },
];

export const graphEdges = [
  { from: "maya", to: "finance", risky: false },
  { from: "finance", to: "exporters", risky: false },
  { from: "exporters", to: "billing", risky: true },
  { from: "nadia", to: "contractors", risky: false },
  { from: "contractors", to: "support-admin", risky: true },
  { from: "support-admin", to: "support", risky: true },
  { from: "service", to: "agents", risky: false },
  { from: "agents", to: "platform", risky: true },
  { from: "platform", to: "aws", risky: true },
];
